// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBKgFD6FKojqvV04cIZqnuHfJkdI88OS0',
    appId: '1:1015209164858:web:4e465a396fcdb86f08b503',
    messagingSenderId: '1015209164858',
    projectId: 'syta-app',
    authDomain: 'syta-app.firebaseapp.com',
    storageBucket: 'syta-app.appspot.com',
    measurementId: 'G-SR45N4JD55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHdp6LXjh9xwba_qD6YnOkdb71m9M18p4',
    appId: '1:1015209164858:android:272b1a950e866a3208b503',
    messagingSenderId: '1015209164858',
    projectId: 'syta-app',
    storageBucket: 'syta-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFDwUfvrqe5XyRMIhDyup4hDIdRRMTUkA',
    appId: '1:1015209164858:ios:4921e7d29993764b08b503',
    messagingSenderId: '1015209164858',
    projectId: 'syta-app',
    storageBucket: 'syta-app.appspot.com',
    iosBundleId: 'com.example.sytaClient',
  );
}
